### ISSUE TITLE
When the robot is facing a blank wall with no patterns on it, it sets it's location randomly to somewhere else.

### ISSUE THREAD

**Issue by RedstoneGithub** [ekumenlabs/tangobot#130]
When the robot is facing a blank wall with no patterns on it, it sets it's location randomly to somewhere else. How this can be fixed is by using the odometry from the Kobuki when it's tracking gets lost.

**Comment by jubeira** [comment]
Hi @AyanGithub!

What you propose is possible, but it requires some work. As this project is open source, we encourage anyone to propose and submit enhacements :wink: . This problem in particular is pretty interesting, and it's a small research project in it's own right.

In my opinion, there could be two approaches to solve it:
- The first one would be to detect when Tango loses it's location, and switch to wheel odometry.
- The second one would be to perform some kind of fusion between wheel and Tango odometry, so that the resulting odometry becomes more robust to these kind of situations.

In any case, you should be able to get the odometry from the robot base. The base driver (called [base_controller](https://github.com/ekumenlabs/base_controller) has a ROS node that allows publishing the odometry. Take a look around [here](https://github.com/ekumenlabs/base_controller/blob/kinetic/base_controller_lib/src/main/java/com/ekumen/base_controller/BaseOdomPublisher.java). This driver is already linked in the application, so to get started you can use it as is, without compiling it from source. After you launch that node, you should be able to get the odometry from the base. Then, the problem to solve is how to combine it with Tango's odometry.
